INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (101538,104774,'Tomtar och Trolltyg Collection','/5UMq1DmJva3l7wg3VK641Sfn9D.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (103751,463068,'TÃ¤Ã¤llÃ¤ PohjantÃ¤hden alla (Timo Koivusalo)','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (104606,385650,'The Spiritual Boxer Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (105077,91697,'Battlestar Galactica (Reboot) Collection','/yB7QLUglaZSCFtC30emJEqfGuWi.jpg','/1ynqKxPc4sgDdweAItGt4QL');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (105965,87256,'Beverly Hills Chihuahua Collection','/v7ofpZSklN0m2ecuHUWeO8S6ZUb.jpg','/jOIk7nAwq7rKLFz8h25soLVSSFf.j');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (107096,286948,'Nemesis Collection','/nKAGlTL97Sp1zIy3f6rGEqjyjGG.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (107916,418219,'Carmina - ColecciÃ³n','/6wvV8rtJZifXancPwHwvzd1j6ul.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (108267,460292,'The Lone Ranger (Clayton Moore) Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (110390,356437,'Living Trilogy','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (110588,138968,'The Gingerdead Man Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (111913,112406,'The Aum Shinrikyo Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (113582,435805,'The Man from U.N.C.L.E. Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (114371,114374,'Fist of the North Star:The Legends of the True Savior','/mZujROFuRvGjSzl3MJOfQQvhtpa.jpg','/qvukxg0e');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (116167,95051,'The Up Series','/nLIBjyGeV2TMiv82MmKq5zX9DhG.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (118340,284433,'Guardians of the Galaxy Collection','/iL8mukexAqEg0xK783rG561tdd8.jpg','/jdyyjulTBU8YUYAUvQFj6U1g2Pj.');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (119450,173710,'Planet of the Apes (Reboot) Collection','/qQrEMycfVN2gRlKTLWGn0QdOnSk.jpg','/mepJpyqVtD6P65vgCU1ngGFE');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (123,141290,'The Lord of the Rings Animated Collection','/pQuazFOlGRdn2Lb3oWFJYPeASOc.jpg','/uUG532EWfyhtKDzsA0sLb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (126963,425164,'Dragon Ball Z (Movie) Collection','/2VMZ1zRFPnUQtQp5K4WRXvDYBjh.jpg','/7PcbijxTfwi9vjWEfXdS0ReAw8q.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (128854,280539,'Lassie (Kinofilme)','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (129417,175722,'The Gorky Collection','/2WmOU2S1xlnd7DPiEMcVjS3rk9E.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (129689,314042,'Onomichi Trilogy','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1361,141290,'The Lord of the Rings Animated Collection','/pQuazFOlGRdn2Lb3oWFJYPeASOc.jpg','/uUG532EWfyhtKDzsA0sLb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (137475,237444,'A Golden Christmas Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (139455,256296,'Silent Night,Deadly Night Collection','/4FqLNnITkZza1QKyTd5nprion1y.jpg','/wZM7UP8tdoZLHUgV4Lj5ixSqK');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (140441,301508,'Sadako 3D Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (140485,479971,'SaÄŸ Salim Serisi','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (146,290973,'Crouching Tiger,Hidden Dragon Collection','/8x9ajHWUm5K5rdMRvXe2vhjdLAk.jpg','/fWbparTMpxYDgutCf9LLl');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (146030,146042,'Oskar Luts Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (147,185682,'The Adventures of Antoine Doinel','/66hyq0YtgBjrfT2kB1YJu33UDcy.jpg','/hT6f042PKqsMjt0t8vPEE7yocKj.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1497,1582,'Teenage Mutant Ninja Turtles (Original) Collection','/9TLc09TqYi0Ct3zmUeHGwVxLHhq.jpg','/7dusELv6x1ANRG');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1498,1582,'Teenage Mutant Ninja Turtles (Original) Collection','/9TLc09TqYi0Ct3zmUeHGwVxLHhq.jpg','/7dusELv6x1ANRG');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1499,1582,'Teenage Mutant Ninja Turtles (Original) Collection','/9TLc09TqYi0Ct3zmUeHGwVxLHhq.jpg','/7dusELv6x1ANRG');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (150202,169740,'The Haunting in Connecticut Collection','/6uIGXwqIfdg0IQw3bvfS49VMKHh.jpg','/1sWTV5QaoDnBTTSbElUfe5zB');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (152,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (154,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (157,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (157829,446782,'The Disappearance Of Eleanor Rigby','/xg3F3P9becOjNqYHlMuBcWPXU5G.jpg','/3eyH0cwrBdrSCwKF24oOwy8fO7O.');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (158848,437584,'The Falls Collection','/iER9GZBUBHJo6cWRBuMDzFmmcj5.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1594,937,'The Pink Panther (Original) Collection','/xu6gZ0zGUSR8SC2QLKFaUrX2niM.jpg','/6KE7AguGR3UqwUn5RkzkoBc3MLy');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (159403,160677,'Ninja,Band of Assassins Collection','/jZ9wA4Cr1UeCZSBz3Uz3XaLo7dr.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (159704,173738,'FanthagirÃ² Collection','/t8TwvX5vP1Dukd5regdITIotQK.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (159849,158365,'Why We Fight','/fFYBLu2Hnx27CWLOMd425ExDkgK.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (159849,158365,'Why We Fight','/fFYBLu2Hnx27CWLOMd425ExDkgK.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (168,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1685,1709,'Planet of the Apes Original Collection','/r7TBDEcpBAuFoqdtUz7z2nSeFej.jpg','/eYf3GRnuVCgeFQfEo0qK7ua5rC');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1687,1709,'Planet of the Apes Original Collection','/r7TBDEcpBAuFoqdtUz7z2nSeFej.jpg','/eYf3GRnuVCgeFQfEo0qK7ua5rC');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1688,1709,'Planet of the Apes Original Collection','/r7TBDEcpBAuFoqdtUz7z2nSeFej.jpg','/eYf3GRnuVCgeFQfEo0qK7ua5rC');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1696,105625,'House of 1000 Corpses Collection','/7xpo52YDhHNFG5qdrLxhG58k0ke.jpg','/osLewbX6FJMy1iUcNHm6hoiNH0j.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1698,8412,'Anatomy Collection','/5cMGSefT2oJvzRNwX4IvZQOGO20.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1705,1709,'Planet of the Apes Original Collection','/r7TBDEcpBAuFoqdtUz7z2nSeFej.jpg','/eYf3GRnuVCgeFQfEo0qK7ua5rC');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (172,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (172817,256477,'Saheb Biwi Aur Gangster Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (174,151,'Star Trek:The Original Series Collection','/zcB8KxHA4EapOoZZPAvwgmE1iGK.jpg','/9BQj9hq0aK6yM9Tm2NJ28jg5');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1865,295,'Pirates of the Caribbean Collection','/zT5UKFhq9nk97VGlBbAxlAK8UFN.jpg','/cnKAGbX1rDkAquF2V1wVkptHDJO.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1884,133830,'Star Wars:The Ewok Adventures Collection','/iY9Smj4RQB1ey8QB0JcMtV35uc1.jpg','/9IwrTRYGaxrlbRjCs7UBR');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (193,115570,'Star Trek:The Next Generation Collection','/sddV6vaUC6x37icJS3opIXTXB07.jpg','/r7MMQenUURHhAVHFymtOb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1930,125574,'The Amazing Spider-Man Collection','/moNJa86FgDYy8SWeDym2gnsLLMa.jpg','/aLrNTcLN2kDu9jAJ4tS5haiWGc6.j');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1931,160727,'Stomp the Yard Collection','/2qAqDHlxVS4wOf1Z8mBGpTgp7PB.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1951,1952,'USA:Land of Opportunities Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (1987,278467,'TrilogÃ­a de la violencia de Michael Haneke','/3255nToAwUbGrpwSpZRN6ZEizXp.jpg','/jG44SCGglfYaFeMK2qQM');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (199,115570,'Star Trek:The Next Generation Collection','/sddV6vaUC6x37icJS3opIXTXB07.jpg','/r7MMQenUURHhAVHFymtOb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (200,115570,'Star Trek:The Next Generation Collection','/sddV6vaUC6x37icJS3opIXTXB07.jpg','/r7MMQenUURHhAVHFymtOb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (201,115570,'Star Trek:The Next Generation Collection','/sddV6vaUC6x37icJS3opIXTXB07.jpg','/r7MMQenUURHhAVHFymtOb');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2038,123251,'Iron Eagle Collection','/bAXtdm522B1kVaripFoZLJRU7Ba.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2069,103577,'The Whole Nine/Ten Yards Collection','/m6tkyCcOm4wzklAvsT0jyaM5mgY.jpg','/ttaiuuOHjYLTszcbADBZImqRK5H');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2082,126209,'Halloween (Rob Zombie Series) Collection','/eFfRMP387MTJ4jl0gcE5jvS9XXN.jpg','/tXXPOkcFLcDiJ4OU5SOU3J');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2122,103577,'The Whole Nine/Ten Yards Collection','/m6tkyCcOm4wzklAvsT0jyaM5mgY.jpg','/ttaiuuOHjYLTszcbADBZImqRK5H');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2139,452675,'Cleopatra Jones','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2182,47983,'Killer Tomatoes! Collection','/dle8G0LFT8d4MAS2BFFJhwBjn0Q.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2195,112860,'Kati Collection','/a3NDsarTyXm3BKvGxR1WuRFJ2HW.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (22,295,'Pirates of the Caribbean Collection','/zT5UKFhq9nk97VGlBbAxlAK8UFN.jpg','/cnKAGbX1rDkAquF2V1wVkptHDJO.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2202,280539,'Lassie (Kinofilme)','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (224,457305,'Man of Marble/Iron Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (225,457305,'Man of Marble/Iron Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (229,218406,'Frankenstein (Universal Series)','/2PJYpPHOqnVMXelHV1T4t6zra4i.jpg','/oR3GHwhvOcjn124b7wOZl9SHh8G.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2312,122922,'In the Name of the King Collection','/kxqvnKbKX2MW2xfeGAGvlFSECSj.jpg','/rJaHFKkYvtnjjJ58L9W5KgYxA6w.');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (244,135495,'King Kong (1933 series)','/pM9K6M8wZNypSEXoi2TaeXGpcHu.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2454,420,'The Chronicles of Narnia Collection','/sh6Kn8VBfXotJ6qsvJkdfscxXKR.jpg','/ojjzZUQlqKTsN1T7s5OAVZSjYMH.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2459,351667,'Un Ã©lÃ©phant Ã§a trompe Ã©normÃ©ment','/68zFIZT8xzN4b2LoICzrwjaArEb.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2463,206072,'Running Out Of Time Collection','/5bQraniOdRa6qLcC07Gi2CwngbA.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2487,149191,'Lady Snowblood Collection','/d7ztUEeUpp3mGrD5xoLpi4sH8ad.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (250,95891,'In China They Eat Dogs Collection','/ws7sHs7oVSoVgrLTlEitJ2mJGR8.jpg','/jeH6MaDD1CnZ8TLupBAi0DYWn2F.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (255,185682,'The Adventures of Antoine Doinel','/66hyq0YtgBjrfT2kB1YJu33UDcy.jpg','/hT6f042PKqsMjt0t8vPEE7yocKj.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (256,185682,'The Adventures of Antoine Doinel','/66hyq0YtgBjrfT2kB1YJu33UDcy.jpg','/hT6f042PKqsMjt0t8vPEE7yocKj.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25748,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25749,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25750,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25751,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25752,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25753,115225,'Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (258,185682,'The Adventures of Antoine Doinel','/66hyq0YtgBjrfT2kB1YJu33UDcy.jpg','/hT6f042PKqsMjt0t8vPEE7yocKj.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25833,129453,'Eating Out Series','/uK86CFpVQjP7t4f7U9sIH8FotKN.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25834,114915,'Xtro Collection','/q7nOlgGzUxX85q45pshEaU65P2A.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (259,185682,'The Adventures of Antoine Doinel','/66hyq0YtgBjrfT2kB1YJu33UDcy.jpg','/hT6f042PKqsMjt0t8vPEE7yocKj.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (25934,327598,'To Sir,with Love Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26005,456733,'The 1997 Trilogy','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26028,185667,'The Complete Monterey Pop Festival','/o03FNvDOE2iJWdLl3a6MYZEZ6rd.jpg','/4gC9E9mjsjaoZIY86W7cUbajUJU.');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26123,298820,'American Pie (Spin-off) Collection','/deSui9fZHgArlSmOGxRV1ZBqYTO.jpg','/au9AnpVPqjFfTZIGGuV94276KaL.');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26181,460334,'Bulldog Drummond (Richard Johnson) Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26264,126221,'George of the Jungle Collection','/hUiYlza9hxgAhI203WuzB4HbhDv.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26268,434270,'Lew Harper Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26357,435805,'The Man from U.N.C.L.E. Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26452,314023,'Hercules (Lou Ferrigno) Collection','/8u0CHePdPsVPFzDYhZLXtacKl51.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26483,338327,'Beach Party Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26484,338327,'Beach Party Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26497,223926,'Impy,the small dinosaur Collection','/1PeRZMFnMH3C1NoaSpQoaV1TDHx.jpg','/byBldukCDG11iVBgNocqm9PfERM');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26505,85817,'Arthur and the Invisibles Collection','/lpKNbnUpP0h0cnVwC1LaE9YJB3U.jpg','/e8Q363orc1wi02TSSoDDlil2qXh');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26515,123256,'Pumpkinhead Collection','/3CHL2ezo3OclNNBQ51BRVXHE7Ji.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26581,275873,'Dr. Who Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2662,105625,'House of 1000 Corpses Collection','/7xpo52YDhHNFG5qdrLxhG58k0ke.jpg','/osLewbX6FJMy1iUcNHm6hoiNH0j.jp');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26655,363014,'Like Mike Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26728,373918,'Garfield (Animation) Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26736,413935,'Wizards of Waverly Place Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26914,123218,'Troll Collection','/pyJAsz6hbAzkx5Kw9CvI8jRkOmw.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (26962,264434,'Demonic Toys Collection','/bMrYltBJXNy3z9vE23QQjWnPOeV.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27046,107473,'Ð˜Ñ€Ð¾Ð½Ð¸Ñ ÑÑƒÐ´ÑŒÐ±Ñ‹ (ÐšÐ¾Ð»Ð»ÐµÐºÑ†Ð¸Ñ)','/1DzMfdobDqF67PhAtLiECqLbsqV.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27320,203178,'Jack Frost Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27370,294918,'Paranormal Investigations Collection','/prm7n8B5sNn5rWuZ78kB0mCDPhY.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27376,338327,'Beach Party Collection','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27475,138971,'The Slumber Party Massacre Collection','/hbNwVI7tOr4uWeigv8p7q42MUS7.jpg','/d90ninW84rPsHNajdsxM5fQau');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27548,425280,'Slime City Collection','/8clL5NLfOXFgQzHApmy1Z7tCHv1.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27598,312744,'Madicken','/7EQK8pI2sWZCexDD5YBhtXpLU0N.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2764,257071,'All Stars Collectie','null','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27764,138971,'The Slumber Party Massacre Collection','/hbNwVI7tOr4uWeigv8p7q42MUS7.jpg','/d90ninW84rPsHNajdsxM5fQau');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27769,168545,'Sometimes They Come Back Collection','/wsKdqBC1C5kFTcUWP1TK6QDrBgY.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27771,168545,'Sometimes They Come Back Collection','/wsKdqBC1C5kFTcUWP1TK6QDrBgY.jpg','null');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (27793,91430,'The Neverending Story Collection','/tXuOhgEbXoba7vVIybzGlnycoNq.jpg','/2IqXJIR1i0f6Ngq3A6rjXhQNqFc.jpg');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2787,2794,'The Chronicles of Riddick Collection','/4R2zrqk9KzgxU9UDH3yUUsENXR.jpg','/xb5zyHecWA7UACdiNPXDA3m5HSY.j');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2789,2794,'The Chronicles of Riddick Collection','/4R2zrqk9KzgxU9UDH3yUUsENXR.jpg','/xb5zyHecWA7UACdiNPXDA3m5HSY.j');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (2791,2794,'The Chronicles of Riddick Collection','/4R2zrqk9KzgxU9UDH3yUUsENXR.jpg','/xb5zyHecWA7UACdiNPXDA3m5HSY.j');
INSERT INTO belongs_to_collection (id_movie, id, name, poster_path, backdrop_path) VALUE (285,295,'Pirates of the Caribbean Collection','/zT5UKFhq9nk97VGlBbAxlAK8UFN.jpg','/cnKAGbX1rDkAquF2V1wVkptHDJO.jp');
